#!/bin/bash
mac_out=$(ifconfig 2> /dev/null | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' 2> /dev/null)
linux_out=$(hostname -I 2> /dev/null | awk '{print $1}' 2> /dev/null)

# Will be an empty string if currently offline.
if [ ! -z "$mac_out" ]
then
    echo -n "$mac_out"
elif [ ! -z "$linux_out" ]
then
    echo -n "$linux_out"
else
    echo -n "Offline"
fi
