live_config_reload: true

# macOS default
shell:
  program: /bin/zsh

# this screws with macOS because ALT+3 is #
# therefore, just ignore this special alt behaviour
alt_send_esc: false

window:
  opacity: 1.0
  dimensions:
    columns: 120
    lines: 30
  padding:
    x: 2
    y: 2
  decorations: full

cursor:
  style: Block
  unfocused_hollow: true

mouse:
  hide_when_typing: true

draw_bold_text_with_bright_colors: false

# Base16 Woodland - alacritty color config
# Jay Cornwall (https://jcornwall.com)
colors:
  # Default colors
  primary:
    background: "0x231e18"
    foreground: "0xcabcb1"

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: "0x231e18"
    cursor: "0xcabcb1"

  # Normal colors
  normal:
    black: "0x231e18"
    red: "0xd35c5c"
    green: "0xb7ba53"
    yellow: "0xe0ac16"
    blue: "0x88a4d3"
    magenta: "0xbb90e2"
    cyan: "0x6eb958"
    white: "0xcabcb1"

  # Bright colors
  bright:
    black: "0x9d8b70"
    red: "0xca7f32"
    green: "0x302b25"
    yellow: "0x48413a"
    blue: "0xb4a490"
    magenta: "0xd7c8bc"
    cyan: "0xb49368"
    white: "0xe4d4c8"

# My fav fonts (which I like to change often, and need to be Nerd Font patched):
# family: Meslo LG S DZ
# family: JetBrains Mono NL
# family: Hack
# family: Ubuntu Mono
# family: Fira Code

font:
  size: 14.0
  normal:
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: Bold
  italic:
    family: FiraCode Nerd Font
    style: Regular
  bold_italic:
    family: FiraCode Nerd Font
    style: Bold
  # 'spacing' between lines and letters
  offset:
    x: 0
    y: 2
  glyph_offset:
    x: 0
    y: 2
# debug:
#   render_timer: true
