live_config_reload: true
background_opacity: 1.0

# macOS default
shell:
  program: /bin/zsh

# this screws with macOS because ALT+3 is #
# therefore, just ignore this special alt behaviour
alt_send_esc: false

window:
  dimensions:
    columns: 120
    lines: 30
  padding:
    x: 2
    y: 2
  decorations: full

cursor:
  style: Block
  unfocused_hollow: true

mouse:
  hide_when_typing: true

font:
  size: 14.0
  normal:
    family: Bitstream Vera Sans Mono
    style: Roman
  bold:
    family: Bitstream Vera Sans Mono
    style: Bold
  italic:
    family: Bitstream Vera Sans Mono
    style: Oblique
  bold_italic:
    family: Bitstream Vera Sans Mono
    style: Bold Oblique
  # 'spacing' between lines and letters
  offset:
    x: 0
    y: 4
  glyph_offset:
    x: 0
    y: 2
# debug:
#   render_timer: true
