live_config_reload: true
background_opacity: 1.0

# macOS default
shell:
  program: /bin/zsh

# this screws with macOS because ALT+3 is #
# therefore, just ignore this special alt behaviour
alt_send_esc: false

window:
  dimensions:
    columns: 120
    lines: 30
  padding:
    x: 2
    y: 2
  decorations: full

cursor:
  style: Block
  unfocused_hollow: true

mouse:
  hide_when_typing: true

# My fav fonts:
# family: Meslo LG S DZ
# family: JetBrains Mono NL

font:
  size: 14.0
  normal:
    family: Hack Nerd Font
    style: Regular
  bold:
    family: Hack Nerd Font
    style: Bold
  italic:
    family: Hack Nerd Font
    style: Italic
  bold_italic:
    family: Hack Nerd Font
    style: Bold Italic
  # 'spacing' between lines and letters
  offset:
    x: 0
    y: 2
  glyph_offset:
    x: 0
    y: 2
# debug:
#   render_timer: true
